### ISSUE TITLE
기존 post 없는 경우 오류

### ISSUE THREAD

**Issue by dewyeon** [swimme/react-diary-client#20]
이번에 pull 하고 나니까 mockdata 아니고 api 연동해서 쓰는걸로 코드가 바뀌어서 그런지 로그인 후에 메인페이지가 안나오고 이런 오류가 나요 .......ㅜㅠ
![캡처](https://user-images.githubusercontent.com/44095036/120832688-e5be7880-c59b-11eb-8460-33cc13290dde.PNG)

제 id에 해당하는 기존 글 데이터가 db에 없어서 그런게 아닌가 생각이 드는데, 혹시 mockdata 처럼 제가 직접 db에 글 데이터를 임시로 추가할 수 있나요?
(+) api 연동 부분 구현하고 있는데 제대로 되고 있는건지 확인할때도 필요할 것 같아요...
***
그리고 이것과 별개로 글 목록 화면(메인페이지)에서 post가 없는 경우에 대한 예외처리 코드를 추가해야 할 것 같습니다! post가 없으면 목록은 비워두고 '글이 없습니다'라고 써준다던지..?

**Comment by swimmie0** [comment]
네ㅠㅠ SSR로 posts 데이터를 받아오는 함수가 문제네요.

1. 정인님이 최종 구현하신건 mock data 를 불러오는 건데,  merge 하면서  `post.getPostById(1)`로  merge가 됐네요.
id 1은 제가 쓴 게시글이어서 아마 조회가 안되실거예요ㅠㅠㅎㅎ 그래서 null값으로 넘어가면서 생긴 오류네요. 
다음부터 머지 후 바로 실행오류 확인하겠습니다! 우선은, mock data로 고쳐서 수정해놓았어요.

2. 네 추가가능합니다! 데이터 추가 필요하실 것 같았어요.  음.. 워크벤치 사용하셔야 하는데, 방법은 회의때 알려드릴게요.
우선, 워크벤치 설치해주세요! https://tommypagy.tistory.com/208 

3. post가 없는 경우, 말씀하신 것처럼 문제가 생기니까 그 부분 고려해야겠네요!
