### ISSUE TITLE
메인(목록)페이지 포스트 박스(diarybox)가 겹치는 현상

### ISSUE THREAD

**Issue by dewyeon** [swimme/react-diary-client#27]
홈화면에서 포스트 글이 길면 

해당 박스 길이가 길어지면서 페이지네이션 부분을 침범한다거나
![qq](https://user-images.githubusercontent.com/44095036/121663730-adf68a00-cae1-11eb-83c3-0d9206256ca9.PNG)

이렇게 다른 박스에 겹친다거나 하는 현상이 생기는 걸 발견했습니다 ..
![qqq](https://user-images.githubusercontent.com/44095036/121663743-afc04d80-cae1-11eb-98f7-abaf2027a0d0.PNG)

**Comment by wjddls0828** [comment]
아아 그렇군요 아직 내용 중 첫줄만 보이는 코드 수정을 안해서 그런것같습니다!ㅜㅜ

**Comment by wjddls0828** [comment]
![image](https://user-images.githubusercontent.com/58072776/122221433-3b741880-ceec-11eb-99b7-6beb72841855.png)
코드 수정해서 해당 사항 앞에서부터 30글자까지만 볼 수 있도록 하였습니다!
