### ISSUE TITLE
검색 기능 오류 발견

### ISSUE THREAD

**Issue by wjddls0828** [swimme/react-diary-client#36]
검색창에 검색어를 입력하면 왼쪽 명언이 바뀌는 현상을 발견했습니다.
일단 이슈에 올려두고 
이후 기능이 수정되고 다시 한번 점검해보도록 하겠습니다.

**Comment by swimmie0** [comment]
검색어를 입력하면 상태가 변하면서 컴포넌트가 리렌더링돼서 그럴거에용. 그럼 그 안에 작성하신 랜덤함수도 재작성되거든요.
음 임시방편으로는 useCallback을 사용해서 랜덤함수가 재작성되는걸 막는 방법이 있을 거 같고, 최종적으로는 회의에서 말했듯이 새로고침마다 바뀌는걸 방지해야 하니까 다른 방법으로 수정해야할거 같네용!

**Comment by wjddls0828** [comment]
감사합니다! 이부분 이제 수정되었습니다! ㅎㅎ
