### ISSUE TITLE
일기장 UI 관련 의견

### ISSUE THREAD

**Issue by dewyeon** [swimme/react-diary-client#41]
1. 글 상세페이지 UI 좀더 일기장같은 느낌으로 수정하는 중인데요!
이중에서 어떤게 제일 괜찮은지, 아니면 다른 괜찮은 아이디어나 이미지 있으신지 의견주세요! 
- 구멍 뚫린 노트는 실제 노트를 스캔한 느낌이라 더 실감날 것 같아서 시도해봤는데, 구멍이 검은색으로 보통 되어있어서 글자를 가리길래 그냥 뺐습니다..
- 글이 길어지면 이미지가 세로로 반복이 되도록 했습니다. 그래서 배경 이미지 상단에 노트 스프링(?) 같은게 있는 경우, 진짜 노트같고 예쁘긴 하지만 글이 길어서 아래에서 이미지가 반복이 되는경우엔 이상하더라구요... 그래서 뺐습니다.
### (1) 격자무늬 노트
![노트느낌](https://user-images.githubusercontent.com/44095036/122591360-d3653400-d09d-11eb-8a35-dfc8e30ce180.PNG)
### (2) 코넬노트
![s2](https://user-images.githubusercontent.com/44095036/122591364-d3fdca80-d09d-11eb-863b-3e37763b7a9d.PNG)
### (3) 종이질감
![종이질감](https://user-images.githubusercontent.com/44095036/122591366-d4966100-d09d-11eb-8836-6328289a1995.PNG)

**Comment by dewyeon** [comment]
2. 그리고 일기장느낌을 주기위한 아이디어인데, 헤더에 OOO's Diary 부분에 배경으로 마스킹테이프 이미지같은걸 추가하면 어떨까요? (출처: [tistory 블로그](https://www.google.com/imgres?imgurl=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fc3vrZA%2FbtqOVJXJpcV%2FzSrCmOx01ahNlKPkJu3SF1%2Fimg.png&imgrefurl=https%3A%2F%2Fdo-shiruk.tistory.com%2F9&tbnid=z4oClbnMEZ9kTM&vet=12ahUKEwjRpoWvz6HxAhVI15QKHd-LDXAQMygDegUIARDIAQ..i&docid=cQjZGt4GNExDWM&w=1142&h=1181&q=%EB%A7%88%EC%8A%A4%ED%82%B9%ED%85%8C%EC%9D%B4%ED%94%84%20png%20%EB%AC%B4%EB%A3%8C&hl=ko&ved=2ahUKEwjRpoWvz6HxAhVI15QKHd-LDXAQMygDegUIARDIAQ))
![마스킹테이프 2_](https://user-images.githubusercontent.com/44095036/122592753-ad409380-d09f-11eb-8c6b-c27f34ec6efb.png)

**Comment by swimmie0** [comment]
1. 생각보다 격자노트는 가독성이 안좋아지네여ㅠㅠ 아쉽.. 종이질감이 제일 이쁜데 배경이랑 뭔가 겹치는? 느낌이 들기도하고 흠🧐 
- 혹시 시간되시면 흰 색배경에 박스섀도우 있는 느낌도 봐주실 수 있나요?
- css로 할경우 박스섀도우 예제 사이트 올려봅니다! 각 박스 클릭하면 css copy돼요 그냥 이미지로 하셔도되구요!  https://getcssscan.com/css-box-shadow-examples  

![Blank_Paper_Sheet_1](https://user-images.githubusercontent.com/37537202/122629754-51572880-d0fa-11eb-8efe-81f8ab6e87a3.jpg)

![images](https://user-images.githubusercontent.com/37537202/122629761-5f0cae00-d0fa-11eb-9d60-b140b7ffd365.jpeg)
![36997000-흰색-a4-크기-용지의-설정-벡터](https://user-images.githubusercontent.com/37537202/122629854-f6720100-d0fa-11eb-8b94-222b9436e478.png)


2. 마스킹테이프 좋아요!!! 귀엽!

**Comment by dewyeon** [comment]
오 이런 좋은 사이트가 있군요..! 올려주신 사이트에서 해봤구요 종류가 되게 많아서 몇가지만 해봤어요

### (1)
`box-shadow: rgba(50, 50, 93, 0.25) 0px 30px 60px -12px, rgba(0, 0, 0, 0.3) 0px 18px 36px -18px;`
적절한 그림자

![q](https://user-images.githubusercontent.com/44095036/122630269-7ef1a100-d0fd-11eb-846a-a6f54c04b107.PNG)

### (1.5)
`box-shadow: rgba(0, 0, 0, 0.2) 0px 20px 30px;
`
지금보니 1번이랑 거의 비슷한것같네요.. 그래서 1.5번으로 넣어봤습니다 1.5가 그림자가 살짝 더 연한거같아요

![4](https://user-images.githubusercontent.com/44095036/122630282-87e27280-d0fd-11eb-9b74-cf2f007190c3.PNG)

### (2)
`box-shadow: rgba(0, 0, 0, 0.07) 0px 1px 1px, rgba(0, 0, 0, 0.07) 0px 2px 2px,
    rgba(0, 0, 0, 0.07) 0px 4px 4px, rgba(0, 0, 0, 0.07) 0px 8px 8px,
    rgba(0, 0, 0, 0.07) 0px 16px 16px;
`
튀어나온 입체적인 A4용지느낌+그림자

![2](https://user-images.githubusercontent.com/44095036/122630270-8153fb00-d0fd-11eb-8ad2-f532024005ce.PNG)

### (2.5)
`box-shadow: rgba(0, 0, 0, 0.09) 0px 2px 1px, rgba(0, 0, 0, 0.09) 0px 4px 2px, rgba(0, 0, 0, 0.09) 0px 8px 4px, rgba(0, 0, 0, 0.09) 0px 16px 8px, rgba(0, 0, 0, 0.09) 0px 32px 16px;`
2번이랑 거의비슷해서 2.5로 넣어봤어요 ,, 그림자가 좀 더 진합니당

![7](https://user-images.githubusercontent.com/44095036/122630440-9d0bd100-d0fe-11eb-8b17-f9f8071fb252.PNG)

### (3)
`  box-shadow: rgba(0, 0, 0, 0.15) 0px 3px 3px 0px;
`
조금 입체적인 느낌

![3](https://user-images.githubusercontent.com/44095036/122630280-83b65500-d0fd-11eb-8b9c-a6172f3363a3.PNG)

### (4)
`box-shadow: rgba(0, 0, 0, 0.1) 0px 4px 12px;
`
아주살짝 그림자

![5](https://user-images.githubusercontent.com/44095036/122630288-89ac3600-d0fd-11eb-9e65-c7a43d8de989.PNG)

### (5)
`box-shadow: rgb(38, 57, 77) 0px 20px 30px -10px;`
진한 그림자

![6](https://user-images.githubusercontent.com/44095036/122630290-8c0e9000-d0fd-11eb-9a0a-4c0e4b8e6a33.PNG)

**Comment by swimmie0** [comment]
비교하기 쉽게 올려주셔서 감사합니다! 👍 저는 개인적으로 2,3,4 가 적당해보입니다!

**Comment by wjddls0828** [comment]
오오 저는 3,4번이 괜찮은 것 같습니다! 메모장 같은 느낌으로 좋네요!

**Comment by dewyeon** [comment]
헤더에 마스킹테이프 추가한 느낌은 이렇습니다!
![캡처](https://user-images.githubusercontent.com/44095036/122663437-6fde2200-d1d5-11eb-97c4-f5ec9dae8f58.PNG)

**Comment by swimmie0** [comment]
와 이뻐요...

> 헤더에 마스킹테이프 추가한 느낌은 이렇습니다!
