### ISSUE TITLE
db schema update (0523)

### ISSUE THREAD

**Issue by swimmie0** [swimme/react-diary-client#6]
기획변경에 따라 스키마 수정했습니다~
[schema](https://github.com/swimme/react-diary-client/wiki/Schema) 에서 확인하시고,
https://github.com/swimme/react-diary-client/pull/5/commits/629f4234637fdb16a4d3e849eb04efcd276e5ee6 에서 인터페이스 변경 확인해주세요!

**Comment by dewyeon** [comment]
확인했습니다. 스키마에 따라 인터페이스 모두 알맞게 변경된 것 같아요!
